<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationIcon>猪猪1.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Control\MyTreeView.cs">
      <SubType>Component</SubType>
    </Compile>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.10" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Iplugin\Iplugin.csproj" />
    <ProjectReference Include="..\PetCommon\PetCommon.csproj" />
    <ProjectReference Include="..\Rep\Rep.csproj" />
    <ProjectReference Include="..\WinSystem\WinSystem.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="猪猪1.ico" />
  </ItemGroup>
</Project>